name: Tests

on:
  push:
    branches: [ fix-ci2 ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  CI: true

jobs:
  test:

    strategy:
      matrix:
        python-version:
          - '3.8.x'
          - '3.9.x'
          - '3.10.x'
          - '3.11.x'
          - '3.12.x'
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest

    runs-on: ${{ matrix.os }}

    name: Python ${{ matrix.python-version }} on ${{ matrix.os }} test

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install poetry
          poetry config virtualenvs.create false
          poetry install --no-interaction --no-ansi --without docs --with dev
      
      - name: Set file permissions (Windows)
        if: runner.os == 'Windows'
        run: |
          icacls "/tmp/models/" /grant Everyone:F /T

      - name: Run pytest
        run: |
          poetry run pytest

          